Auction.UI/Controllers/AdminController.cs
using Auction.Model.Models;
using Auction.Service;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Auction.UI.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private IUserService userService;

        public AdminController(IUserService userService)
        {
            this.userService = userService;
        }

        // GET: Admin
        public ActionResult Index()
        {
            var users =Mapper.Map<IEnumerable<UserViewModel>>(userService.GetUsers());
            return View(users);
        }

        [HttpGet]
        public ActionResult EditUser(int id = 0)
        {
            var user =Mapper.Map<UserViewModel>(userService.GetUser(id));
            if (user == null)
                return HttpNotFound();
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUser(UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                var user = Mapper.Map<User>(userViewModel);
                userService.Update(user);
                ViewBag.Result = "Updated";
            }
            else
                ViewBag.Result = "Error";
            return View(userViewModel);
        }

        public ActionResult SearchUser(string search)
        {
           var users = Mapper.Map<IEnumerable<UserViewModel>>(userService.Search(search));            
            return View("Index", users);

        }
    }
}

Auction.UI/Controllers/LotController.cs
using Auction.Model.Models;
using Auction.Service;
using Auction.UI.Helpers;
using Auction.UI.ViewModels;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
namespace Auction.UI.Controllers
{
    public class LotController : Controller
    {

        private ILotService lotService;
        private IUserService userService;
        private IImageService imageService;
        public LotController(ILotService lotService, IUserService userService,IImageService imageService)
        {
            this.lotService = lotService;
            this.userService = userService;
            this.imageService = imageService;
        }

        [Authorize]
        [HttpGet]
        public ActionResult Add()
        {
            if (TempData.ContainsKey("imgCount"))
                TempData.Remove("imgCount");
            TempData.Add("imgCount", 0);
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(AddLotViewModel model)
        {
            if (ModelState.IsValid)
            {
                var lot = Mapper.Map<Lot>(model);
                lot.Images = new List<Image>();
                if (model.Urls != null)
                {
                    foreach (var u in model.Urls)
                    {
                        lot.Images.Add(new Image()
                        {
                            Url = u
                        });
                    }
                }
                TempData.Remove("imgCount");
                var user = userService.GetUserByEmail(User.Identity.Name);
                lot.Seller = user;
                user.Lots.Add(lot);
                lotService.AddLot(lot);
                return RedirectToAction("Details", new { id = lot.LotId });
            }

            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult MakeBet(int id = 0)
        {
            var lot = lotService.GetLot(id);
            if (lot == null)
                return HttpNotFound();
            var user = userService.GetUserByEmail(User.Identity.Name);

            bool isBetMade = lotService.MakeBet(user.UserId, lot.LotId);
                if (Request.IsAjaxRequest())
            {
                if (isBetMade)
                {
                    var betViewModel = Mapper.Map<BetViewModel>(lot.Bets.Last());
                   
                    return PartialView("_BetPartial", betViewModel);
                }
                return Json(new { success = false, }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                if (isBetMade)
                    return RedirectToAction("Details", new { id = lot.LotId });
                else
                    return RedirectToAction("Details", new { id = lot.LotId });
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(int id = 0)
        {

            var lot = lotService.GetLot(id);
            if (lot == null)
                return HttpNotFound();
            if (lot.Seller.Email == User.Identity.Name || User.IsInRole("admin"))
                return View(lot);
            else
                return new HttpUnauthorizedResult();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LotViewModel lotViewModel)
        {
            if (ModelState.IsValid)
            {
                if (lotViewModel.Seller.Email == User.Identity.Name || User.IsInRole("admin"))
                {
                    var lot = Mapper.Map<Lot>(lotViewModel);
                    lotService.Update(lot);
                    return View(lotViewModel);
                }
                else
                    return new HttpUnauthorizedResult();
            }
            return View(lotViewModel);
        }


        public ActionResult Details(int id = 0)
        {

            var lot = lotService.GetLot(id);
            if (lot == null)
                return HttpNotFound();
            var model = Mapper.Map<LotDetailsViewModel>(lot);
            if (TempData.ContainsKey("imgCount"))
                TempData.Remove("imgCount");
            TempData.Add("imgCount", model.Images.Count());
            return View(model);
        }


        public ActionResult Upload(HttpPostedFileBase img)
        {
            if (img != null && Utils.IsSupportedMimeType(img.ContentType))
            {                            
                int count = (int)TempData["imgCount"];
                if (count < 3)                {
                    TempData["imgCount"] = ++count;
                    var path = Guid.NewGuid().ToString();
                    imageService.StoreImage(path, img.InputStream);
                    var priviewPath = imageService.GetResizedUrl(path, 200, 200);
                        return Json(new { success = true, img = path, preview_path = priviewPath });
                }

            }

            return Json(new { success = false, result = "error" });
        }

    }
}

Auction.UI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="HandheldFriendly" content="true" />
    <meta name="MobileOptimized" content="320" />

    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/Brushed")
    @RenderSection("styles", required: false)
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900' rel='stylesheet' type='text/css'>
</head>
<body>
    <header>
        <div class="sticky-nav">
            <a id="mobile-nav" class="menu-nav" href="#menu-nav"></a>

            <div id="logo">
                <a id="goUp" href="#home-slider">Auction</a>
            </div>

            <nav id="menu">
                <ul id="menu-nav">
                    <li class="current"><a href=@Url.Action("Index","Home") class="external">Home</a></li>
                    <li><a href="#work">Categories</a></li>
                    <li><a href=@Url.Action("Add","Lot") class="external">Add Lot</a></li>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li><a href=@Url.Action("Login","Account") class="external">Login</a></li>
                    }
                    else
                    {
                        <li>@User.Identity.Name</li>
                        <li><a href=@Url.Action("LogOff","Account") class="external">Log out</a></li>
                    }
                    <li><a href=@Url.Action("About","Home") class="external">About Us</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <div class="page">   
        <div class="span5 offset7">
            @using (Html.BeginForm("SearchUser", "Admin", FormMethod.Post, new { @class = "contact-form", role = "form" }))
            {
                <p>
                    @Html.TextBox("search") <br />
                    <input type="submit" value="Search" class="submit" />
                </p>
            }
        </div>    
        @RenderBody()
    </div>

    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    @Scripts.Render("~/Scripts/Jquery")
    @Scripts.Render("~/Scripts/Brushed")
    @RenderSection("scripts", required: false)
</body>
</html>

Auction.UI/Views/Shared/_BetPartial.cshtml
@model Auction.Model.Models.BetViewModel

<li><a href="@Url.Action("Details","Account",new {id = Model.User.UserId })">@Model.User.DisplayName</a> make a bet --> @Model.Amount (@Model.Date)</li>

Auction.UI/Views/Shared/_BetsPartial.cshtml
@model IEnumerable<Auction.Model.Models.BetViewModel>

@if (Model == null || Model.Count() == 0)
{
    <ul id="bets">
        <li>No Bets yet</li>
    </ul>
}
else
{
    <div class="accordion-group" >
        <div class="accordion-heading accordionize">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionArea" href="#@Model.First().LotId">
                All Bets
                <span class="font-icon-arrow-simple-down"></span>
            </a>
        </div>
        <div id="@Model.First().LotId" class="accordion-body collapse">
            <div class="accordion-inner">
                <ul id="bets" >
                    @foreach (var b in Model)
                    {
                        {Html.RenderPartial("_BetPartial", b); }                    
                    }

                    </ul>

            </div>
        </div>
    </div>
}

Auction.UI/Views/Shared/_ImagePartial.cshtml
@model Auction.Model.Models.ImageViewModel
<li class="item-thumbs span3 design">

    <a class="hover-wrap fancybox" data-fancybox-group="gallery"  href=@Model.Url>
        <span class="overlay-img-thumb font-icon-zoom-in"></span>
    </a>
    <img src=@Model.Url >
</li>     

Auction.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="HandheldFriendly" content="true" />
    <meta name="MobileOptimized" content="320" />

    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/Brushed")
    @RenderSection("styles", required: false)
</head>
<body>
    <header>
        <div class="sticky-nav">
            <a id="mobile-nav" class="menu-nav" href="#menu-nav"></a>

            <div id="logo">
                <a id="goUp">Auction</a>
            </div>

            <nav id="menu">
                <ul id="menu-nav">
                    <li class="current"><a href=@Url.Action("Index","Home") class="external">Home</a></li>
                    <li><a href="#work">Categories</a></li>
                    <li><a href=@Url.Action("Add","Lot") class="external">Add Lot</a></li>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li><a href=@Url.Action("Login","Account") class="external">Login</a></li>
                    }
                    else
                    {
                        <li>@User.Identity.Name</li>
                        <li><a href=@Url.Action("LogOff","Account") class="external">Log out</a></li>
                    }
                    <li><a href=@Url.Action("About","Home") class="external">About Us</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <div class="page">
        <div class="span4 offset8">
            @using (Html.BeginForm("Search", "Home", FormMethod.Post, new { @class = "contact-form", role = "form" }))
            {
                <p>
                    @Html.TextBox("search") <br />
                    <input type="submit" value="Search" class="submit" />
                </p>
            }
        </div>
        @RenderBody()
    </div>

    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - Все равно никто сюда не посмотрит</p>
    </footer>

    @Scripts.Render("~/Scripts/Jquery")
    @Scripts.Render("~/Scripts/Brushed")
    @RenderSection("scripts", required: false)
</body>
</html>

Auction.UI/Views/Shared/_LotPartial.cshtml
@model Auction.Model.Models.LotViewModel
<li class="item-thumbs span3 design">
    <!-- Fancybox - Gallery Enabled - Title - Full Image -->
    <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="@Model.Title" href=@(Model.Images?.First()?.Url ?? Url.Content( "~/Images/no_image.jpg" ))>
        <span class="overlay-img">@Model.Title @Model.CurrentCost $</span>
        <span class="overlay-img-thumb font-icon-resize-full"></span>
    </a>
    <!-- Thumb Image and Description -->
   <img src=@(Model.Images?.First()?.Url ?? Url.Content( "~/Images/no_image.jpg") ) alt="@Model.Description <a href=@Url.Action("Details","Lot",new { id = Model.LotId}) >More...<a>" >
    <a href=@Url.Action("Details","Lot",new { id = Model.LotId})>@Model.Title</a>
</li>     